stages:
  - test
  - deploy
  - deploy-remote

local_deploy:
  stage: deploy
  script: 
    - npm install
    - npm run dev -- --host > /dev/null 2>&1 &

remote_deploy:
  stage: deploy-remote
  script:
    - npm install
    - tsuru app deploy --app drp57 --dockerfile .

test:
  stage: test
  script: echo "Testing"
  environment: test
