cache:
  paths:
    - node_modules/

      #deploy:
      # stage: deploy
      # script: npm install; npm run dev -- --host

deploy:
        stage: deploy
        script:
                - npm install
                - tsuru app deploy --app drp57 ./

test:
  stage: test
  script: echo "Testing"
  environment: test
