stages:
  - test
  - deploy

deploy:
  stage: deploy
  script:
    - tsuru app deploy --app drp57-webapp --dockerfile .
  only:
    - master

test:
  stage: test
  script: echo "Testing"
  environment: test
