cache:
  paths:
    - node_modules/

local_deploy:
  stage: local_deploy
  script: 
    - npm install
    - npm run dev -- --host

remote_deploy:
  stage: remote_deploy
  script:
    - npm install
    - tsuru app deploy --app drp57 ./

test:
  stage: test
  script: echo "Testing"
  environment: test
